"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

type Language = "id" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  id: {
    "nav.about": "Tentang YAPIM",
    "nav.academic": "Pendidikan & Akademik",
    "nav.life": "Kehidupan Siswa",
    "nav.news": "Berita & Pengumuman",
    "nav.admission": "Penerimaan",
    "nav.alumni": "Alumni & Karir",
    "nav.staff": "Guru & Staf",
    "hero.badge": "Selamat Datang di Portal Resmi",
    "hero.title": "Membangun Generasi Unggul & Berkarakter",
    "hero.subtitle": "SMA-SMKS YAPIM Taruna Pandan didedikasikan untuk mencetak pemimpin masa depan melalui pendidikan berkualitas tinggi, integritas moral, dan wawasan global.",
    "cta.primary": "Kenali Kami Lebih Dekat",
    "cta.secondary": "Jelajahi Fasilitas",
    "welcome.badge": "Sambutan Kepala Sekolah",
    "welcome.title": "Berdedikasi untuk Keunggulan Pendidikan Sumatera Utara",
    "welcome.subtitle": "Visi kami adalah membentuk pemimpin masa depan yang kompeten dan religius.",
    "welcome.quote": "Pendidikan bukan sekadar transfer ilmu, melainkan proses panjang dalam membentuk karakter, etika, dan landasan moral generasi masa depan.",
    "welcome.name": "Parunggulan Tobing",
    "welcome.role": "Kepala Sekolah SMA-SMKS YAPIM",
    "stats.title": "Pencapaian Institusi",
    "stats.students": "Siswa Aktif",
    "stats.alumni": "Alumni Sukses",
    "stats.staff": "Guru & Staf",
    "stats.graduation": "Tingkat Kelulusan",
    "footer.desc": "Lembaga pendidikan menengah atas terkemuka di Sumatera Utara yang berdedikasi menghasilkan lulusan dengan keunggulan akademik, karakter mulia, dan wawasan global.",
    "footer.links": "Tautan Cepat",
    "footer.services": "Layanan Online",
    "footer.contact": "Hubungi Kami",
    "lang.switch": "English",

    // Privacy Page
    "privacy.hero.badge": "Legal & Privasi",
    "privacy.hero.title": "Kebijakan Privasi",
    "privacy.hero.subtitle": "Perlindungan data pribadi Anda adalah prioritas kami",
    "privacy.lastUpdated": "Terakhir Diperbarui",
    "privacy.intro.title": "Pendahuluan",
    "privacy.intro.p1": "SMA-SMKS YAPIM Taruna Pandan (\"kami\") berkomitmen untuk melindungi dan menghormati privasi Anda. Kebijakan Privasi ini menjelaskan bagaimana kami mengumpulkan, menggunakan, mengungkapkan, dan melindungi informasi pribadi Anda saat Anda menggunakan website kami.",
    "privacy.intro.p2": "Dengan mengakses atau menggunakan website kami, Anda menyetujui pengumpulan dan penggunaan informasi sesuai dengan kebijakan ini.",
    "privacy.data.title": "Data yang Kami Kumpulkan",
    "privacy.data.personal": "Informasi yang Anda Berikan",
    "privacy.data.auto": "Informasi yang Dikumpulkan Secara Otomatis",
    "privacy.usage.title": "Bagaimana Kami Menggunakan Data Anda",
    "privacy.usage.education": "Untuk Pendidikan",
    "privacy.usage.eduDesc": "Mengelola pembelajaran, nilai, dan absensi siswa",
    "privacy.usage.communication": "Untuk Komunikasi",
    "privacy.usage.commDesc": "Mengirim informasi penting kepada orang tua dan siswa",
    "privacy.usage.registration": "Untuk Pendaftaran",
    "privacy.usage.regDesc": "Memproses pendaftaran siswa baru (PPDB)",
    "privacy.usage.improvement": "Untuk Perbaikan",
    "privacy.usage.impDesc": "Meningkatkan kualitas layanan dan website",
    "privacy.rights.title": "Hak Anda atas Data Pribadi",
    "privacy.rights.access": "Akses",
    "privacy.rights.accessDesc": "Anda berhak mengetahui data apa saja yang kami simpan tentang Anda",
    "privacy.rights.correct": "Koreksi",
    "privacy.rights.correctDesc": "Anda dapat memperbarui data yang tidak akurat",
    "privacy.rights.delete": "Hapus",
    "privacy.rights.deleteDesc": "Anda dapat meminta penghapusan data pribadi Anda",
    "privacy.rights.reject": "Tolak",
    "privacy.rights.rejectDesc": "Anda dapat menolak penggunaan data untuk tujuan tertentu",
    "privacy.security.title": "Keamanan Data",
    "privacy.security.desc": "Kami menerapkan berbagai langkah keamanan untuk melindungi data pribadi Anda",
    "privacy.security.encryption": "Enkripsi data saat transmisi",
    "privacy.security.access": "Akses terbatas untuk authorized personnel",
    "privacy.security.audit": "Regular security audits",
    "privacy.security.backup": "Backup data secara berkala",
    "privacy.contact.title": "Pertanyaan tentang Privasi?",
    "privacy.contact.desc": "Jika Anda memiliki pertanyaan tentang Kebijakan Privasi ini atau perlakuan data pribadi Anda, silakan hubungi kami",
    "privacy.cta.title": "Butuh Bantuan Lainnya?",
    "privacy.cta.subtitle": "Tim kami siap membantu Anda dengan pertanyaan atau kebutuhan lainnya",
    "privacy.cta.help": "Pusat Bantuan",
    "privacy.cta.contact": "Hubungi Kami",

    // Terms Page
    "terms.hero.badge": "Legal & Ketentuan",
    "terms.hero.title": "Syarat & Ketentuan",
    "terms.hero.subtitle": "Aturan penggunaan website dan layanan SMA-SMKS YAPIM Taruna Pandan",
    "terms.lastUpdated": "Terakhir Diperbarui",
    "terms.intro.title": "1. Pendahuluan",
    "terms.intro.p1": "Selamat datang di website resmi SMA-SMKS YAPIM Taruna Pandan. Dengan mengakses atau menggunakan website kami, Anda menyetujui untuk terikat oleh Syarat & Ketentuan ini.",
    "terms.intro.p2": "Jika Anda tidak setuju dengan bagian manapun dari ketentuan ini, harap jangan menggunakan website kami.",
    "terms.usage.title": "2. Ketentuan Penggunaan Website",
    "terms.usage.age": "Usia Pengguna",
    "terms.usage.ageDesc": "Website ini ditujukan untuk pengguna berusia 18 tahun ke atas. Pengguna di bawah 18 tahun harus dengan pengawasan orang tua atau wali.",
    "terms.usage.account": "Akun Pengguna",
    "terms.usage.accountDesc": "Anda bertanggung jawab untuk menjaga kerahasiaan informasi akun Anda dan membatasi akses ke komputer atau perangkat Anda.",
    "terms.usage.prohibited": "Perilaku yang Dilarang",
    "terms.usage.prohibitedDesc": "Menggunakan website untuk tujuan ilegal, mencoba meretas atau merusak sistem keamanan, mengunggah konten yang merugikan pihak lain, mengirim spam atau pesan tidak diinginkan, meniru orang atau entitas lain.",
    "terms.copyright.title": "3. Hak Cipta & Konten",
    "terms.copyright.ownership": "Kepemilikan Konten",
    "terms.copyright.ownershipDesc": "Semua konten di website ini (teks, gambar, logo, video) adalah hak cipta SMA-SMKS YAPIM Taruna Pandan atau pihak ketiga yang berwenang.",
    "terms.copyright.allowed": "Penggunaan yang Diperbolehkan",
    "terms.copyright.allowedDesc": "Anda diperbolehkan melihat, mengunduh, atau mencetak konten untuk penggunaan pribadi dan non-komersial.",
    "terms.copyright.prohibited": "Penggunaan yang Dilarang",
    "terms.copyright.prohibitedDesc": "Diperbolehkan memodifikasi, mendistribusikan, atau menggunakan konten untuk tujuan komersial tanpa izin tertulis dari kami.",
    "terms.liability.title": "4. Pembatasan Tanggung Jawab",
    "terms.liability.desc": "Website kami disediakan \"sebagaimana adanya\" tanpa jaminan dalam bentuk apapun. Kami tidak menjamin:",
    "terms.liability.availability": "Website akan selalu tersedia atau bebas dari kesalahan",
    "terms.liability.accuracy": "Informasi di website akurat atau lengkap",
    "terms.liability.security": "Website aman dari virus atau komponen berbahaya lainnya",
    "terms.privacy.title": "5. Privasi & Data Pribadi",
    "terms.privacy.desc": "Penggunaan data pribadi Anda diatur oleh Kebijakan Privasi kami. Dengan menggunakan website ini, Anda menyetujui pengolahan data sesuai dengan kebijakan tersebut.",
    "terms.privacy.link": "Lihat Kebijakan Privasi →",
    "terms.changes.title": "6. Perubahan Ketentuan",
    "terms.changes.desc": "Kami berhak mengubah Syarat & Ketentuan ini kapan saja. Perubahan akan ditampilkan di halaman ini dan tanggal \"Terakhir Diperbarui\" akan diperbarui. Penggunaan Anda yang terus menerus setelah perubahan berarti Anda menerima ketentuan baru.",
    "terms.contact.title": "7. Hubungi Kami",
    "terms.contact.desc": "Jika Anda memiliki pertanyaan tentang Syarat & Ketentuan ini, silakan hubungi kami",
    "terms.contact.email": "Email",
    "terms.contact.phone": "Telepon",
    "terms.contact.button": "Hubungi Kami",
    "terms.cta.title": "Butuh Informasi Lebih Lanjut?",
    "terms.cta.subtitle": "Tim kami siap membantu menjawab pertanyaan Anda",
    "terms.cta.help": "Pusat Bantuan",
    "terms.cta.contact": "Hubungi Kami",

    // Karir Page
    "karir.hero.badge": "Karir & Alumni",
    "karir.hero.title": "Bergabung Bersama Kami",
    "karir.hero.subtitle": "Bangun karir di pendidikan atau terhubung dengan network alumni kami",
    "karir.stats.teachers": "Guru & Staff",
    "karir.stats.alumni": "Alumni",
    "karir.stats.experience": "Tahun Pengalaman",
    "karir.stats.accreditation": "Akreditasi",
    "karir.positions.badge": "Lowongan Tersedia",
    "karir.positions.title": "Posisi yang Sedang Dibuka",
    "karir.positions.subtitle": "Bergabunglah dengan tim pendidik profesional kami untuk mencetak generasi unggul",
    "karir.positions.fullTime": "Full Time",
    "karir.positions.requirements": "Persyaratan",
    "karir.positions.apply": "Kirim Lamaran",
    "karir.positions.spontan": "Kirim CV Spontan",
    "karir.positions.noPosition": "Tidak menemukan posisi yang sesuai? Kirim CV Anda ke kami untuk dipertimbangkan di masa depan.",
    "karir.alumni.badge": "Alumni Network",
    "karir.alumni.title": "Keuntungan Menjadi Alumni",
    "karir.alumni.subtitle": "Bergabung dengan network alumni YAPIM untuk berbagai manfaat karir dan profesional",
    "karir.alumni.networking": "Networking",
    "karir.alumni.networkingDesc": "Terhubung dengan ribuan alumni YAPIM",
    "karir.alumni.career": "Info Karir",
    "karir.alumni.careerDesc": "Akses lowongan kerja eksklusif",
    "karir.alumni.events": "Event Alumni",
    "karir.alumni.eventsDesc": "Reuni dan gathering rutin",
    "karir.alumni.mentoring": "Mentoring",
    "karir.alumni.mentoringDesc": "Program mentoring untuk siswa",
    "karir.testimonials.badge": "Testimoni",
    "karir.testimonials.title": "Kata Alumni & Guru",
    "karir.cta.title": "Siap Bergabung?",
    "karir.cta.subtitle": "Jadilah bagian dari tim pendidik YAPIM atau bergabung dengan network alumni kami",
    "karir.cta.apply": "Lamar Sekarang",
    "karir.cta.alumni": "Portal Alumni",

    // Bantuan Page
    "bantuan.hero.badge": "Pusat Bantuan",
    "bantuan.hero.title": "Bagaimana Kami Bisa Membantu?",
    "bantuan.hero.subtitle": "Temukan jawaban untuk pertanyaan umum atau hubungi tim kami",
    "bantuan.quicklinks.title": "Cepat Temukan yang Anda Butuhkan",
    "bantuan.quicklinks.ppdb": "Pendaftaran Siswa Baru",
    "bantuan.quicklinks.akademik": "Informasi Akademik",
    "bantuan.quicklinks.kontak": "Hubungi Kami",
    "bantuan.quicklinks.galeri": "Galeri Sekolah",
    "bantuan.quicklinks.karir": "Karir & Alumni",
    "bantuan.faq.badge": "FAQ",
    "bantuan.faq.title": "Pertanyaan yang Sering Diajukan",
    "bantuan.faq.subtitle": "Cari jawaban untuk pertanyaan umum seputar pendaftaran, akademik, dan fasilitas sekolah",
    "bantuan.faq.q1.question": "Bagaimana cara mendaftar sebagai siswa baru (PPDB)?",
    "bantuan.faq.q1.answer": "Pendaftaran siswa baru dapat dilakukan secara online melalui halaman PPDB di website kami. Anda perlu mengisi formulir pendaftaran, mengunggah dokumen yang diperlukan (ijazah, KK, akta kelahiran), dan membayar biaya pendaftaran. Informasi lengkap tersedia di halaman /ppdb.",
    "bantuan.faq.q2.question": "Apa syarat pendaftaran untuk SMA dan SMK?",
    "bantuan.faq.q2.answer": "Untuk SMA: Lulusan SMP/MTs dengan nilai rapor minimal rata-rata 75. Untuk SMK: Lulusan SMP/MTs dengan ketentuan khusus sesuai jurusan (TKR membutuhkan fisik yang baik, TKJ tertarik pada jaringan komputer, dll). Dokumen yang diperlukan: Ijazah/SKL, KK, Akta Kelahiran, dan Pas Foto.",
    "bantuan.faq.q3.question": "Bagaimana cara menghubungi pihak sekolah?",
    "bantuan.faq.q3.answer": "Anda dapat menghubungi kami melalui: Telepon (0631) 372375, Email: yapim_pandan@yahoo.com, atau datang langsung ke sekolah di JL. AHMAD YANI PANDAN. Jam operasional: Senin - Jumat, 07.00 - 15.00 WIB.",
    "bantuan.faq.q4.question": "Apakah ada beasiswa untuk siswa berprestasi?",
    "bantuan.faq.q4.answer": "Ya, YAPIM menyediakan beasiswa untuk siswa berprestasi akademik dan non-akademik. Beasiswa diberikan berdasarkan evaluasi rapor semester dan prestasi di tingkat kabupaten/provional/nasional. Hubungi bagian kesiswaan untuk informasi lebih lanjut.",
    "bantuan.faq.q5.question": "Bagaimana sistem e-learning di YAPIM?",
    "bantuan.faq.q5.answer": "YAPIM menggunakan platform e-learning untuk mendukung pembelajaran hybrid. Siswa dapat mengakses materi, tugas, dan kuis secara online. Login menggunakan NIS yang diberikan saat pendaftaran. Panduan lengkap tersedia di halaman /elearning.",
    "bantuan.faq.q6.question": "Apa saja jurusan yang tersedia di SMK?",
    "bantuan.faq.q6.answer": "SMK YAPIM Taruna Pandan menyediakan jurusan: 1) TKR (Teknik Kendaraan Ringan) - Otomotif, 2) TKJ (Teknik Komputer dan Jaringan) - IT dan Jaringan. Kedua jurusan memiliki fasilitas lengkap dan kerjasama dengan industri.",
    "bantuan.contact.badge": "Kontak Kami",
    "bantuan.contact.title": "Masih Punya Pertanyaan?",
    "bantuan.contact.subtitle": "Tim kami siap membantu Anda. Hubungi kami melalui saluran berikut",
    "bantuan.contact.phoneTitle": "Telepon",
    "bantuan.contact.emailTitle": "Email",
    "bantuan.contact.addressTitle": "Alamat",
    "bantuan.contact.hoursTitle": "Jam Operasional",
    "bantuan.contact.call": "Hubungi",
    "bantuan.contact.fullForm": "Lihat Formulir Kontak Lengkap",
    "bantuan.cta.title": "Ingin Berbicara dengan Tim Kami?",
    "bantuan.cta.subtitle": "Kami siap membantu menjawab pertanyaan dan memberikan dukungan yang Anda butuhkan",
    "bantuan.cta.email": "Kirim Email",
    "bantuan.cta.phone": "Telepon",

    // Portal Siswa Page
    "portal.hero.badge": "Portal Siswa",
    "portal.hero.title": "Sistem Informasi Siswa",
    "portal.hero.subtitle": "Akses jadwal, nilai, dan informasi akademik dalam satu portal terintegrasi",
    "portal.stats.access": "Akses",
    "portal.stats.students": "Siswa Aktif",
    "portal.stats.features": "Fitur Utama",
    "portal.stats.digital": "Digital",
    "portal.features.title": "Semua yang Anda Butuhkan",
    "portal.features.subtitle": "Portal siswa menyediakan berbagai fitur untuk memudahkan kegiatan belajar",
    "portal.features.schedule": "Jadwal Pelajaran",
    "portal.features.scheduleDesc": "Akses jadwal pelajaran lengkap untuk setiap semester",
    "portal.features.grades": "Nilai & Rapor",
    "portal.features.gradesDesc": "Lihat nilai tugas, ujian, dan rapor semester secara online",
    "portal.features.attendance": "Absensi",
    "portal.features.attendanceDesc": "Pantau kehadiran dan record absensi harian",
    "portal.features.materials": "Materi Pembelajaran",
    "portal.features.materialsDesc": "Akses materi dan resource pembelajaran digital",
    "portal.features.erapor": "E-Rapor",
    "portal.features.eraporDesc": "Sistem rapor elektronik yang terintegrasi",
    "portal.features.profile": "Data Pribadi",
    "portal.features.profileDesc": "Kelola data diri dan informasi akademik",
    "portal.login.badge": "Cara Login",
    "portal.login.title": "Masuk ke Portal Siswa",
    "portal.login.subtitle": "Ikuti langkah mudah berikut untuk mengakses portal siswa",
    "portal.login.step1": "Buka Halaman Portal",
    "portal.login.step1Desc": "Kunjungi halaman portal siswa melalui tombol di bawah",
    "portal.login.step2": "Masukkan NIS",
    "portal.login.step2Desc": "Gunakan Nomor Induk Siswa sebagai username",
    "portal.login.step3": "Masukkan Password",
    "portal.login.step3Desc": "Password default adalah tanggal lahir (DDMMYYYY)",
    "portal.login.step4": "Ganti Password",
    "portal.login.step4Desc": "Segera ganti password setelah login pertama",
    "portal.login.forgot": "Lupa Password?",
    "portal.login.forgotDesc": "Hubungi admin sekolah untuk reset",
    "portal.parent.badge": "Untuk Orang Tua",
    "portal.parent.title": "Pantau Anak Anda Secara Real-Time",
    "portal.parent.subtitle": "Portal siswa juga memudahkan orang tua untuk memantau perkembangan akademik anak",
    "portal.parent.performance": "Pantau Performa Anak",
    "portal.parent.performanceDesc": "Orang tua dapat memantau nilai, kehadiran, dan aktivitas belajar anak secara real-time",
    "portal.parent.communication": "Komunikasi dengan Guru",
    "portal.parent.communicationDesc": "Hubungi guru wali kelas atau mata pelajaran langsung melalui portal",
    "portal.parent.calendar": "Info Kalender Akademik",
    "portal.parent.calendarDesc": "Akses jadwal ujian, libur, dan event penting sekolah",
    "portal.cta.title": "Siap Mengakses Portal Siswa?",
    "portal.cta.subtitle": "Login sekarang untuk mengakses semua informasi akademik Anda",
    "portal.cta.login": "Login ke Portal",
    "portal.cta.help": "Butuh Bantuan?",
    "portal.cta.comingSoon": "* Portal Siswa dalam pengembangan. Segera hadir!",

    // E-Learning Page
    "elearning.hero.badge": "E-Learning YAPIM",
    "elearning.hero.title": "Belajar Digital,",
    "elearning.hero.title2": "Masa Depan Cerah",
    "elearning.hero.subtitle": "Platform pembelajaran online modern untuk siswa SMA-SMKS YAPIM Taruna Pandan",
    "elearning.stats.materials": "Materi Aktif",
    "elearning.stats.students": "Siswa",
    "elearning.stats.access": "Akses",
    "elearning.stats.online": "Online",
    "elearning.about.badge": "Tentang E-Learning",
    "elearning.about.title": "Apa itu E-Learning YAPIM?",
    "elearning.about.desc": "E-Learning YAPIM adalah platform pembelajaran digital yang dirancang untuk mendukung proses belajar mengajar secara hybrid. Siswa dapat mengakses materi, mengerjakan tugas, dan berdiskusi dengan guru secara online kapan saja dan di mana saja.",
    "elearning.about.forStudents": "Untuk Siswa",
    "elearning.about.forStudentsDesc": "Belajar lebih fleksibel dengan akses materi digital, kerjakan tugas online, dan diskusi dengan teman sekelas.",
    "elearning.about.forTeachers": "Untuk Guru",
    "elearning.about.forTeachersDesc": "Kelola pembelajaran digital dengan mudah. Upload materi, buat quiz, dan pantau progress siswa.",
    "elearning.features.badge": "Fitur Unggulan",
    "elearning.features.title": "Kenapa E-Learning YAPIM?",
    "elearning.features.digitalMaterials": "Materi Digital",
    "elearning.features.digitalMaterialsDesc": "Akses materi pembelajaran dalam berbagai format: teks, video, dan slide",
    "elearning.features.quiz": "Quiz & Assignment",
    "elearning.features.quizDesc": "Kerjakan tugas dan ujian online dengan sistem penilaian otomatis",
    "elearning.features.forum": "Forum Diskusi",
    "elearning.features.forumDesc": "Diskusi dengan guru dan teman sekelas secara online",
    "elearning.features.tracking": "Tracking Progress",
    "elearning.features.trackingDesc": "Pantau perkembangan belajar dan pencapaian Anda",
    "elearning.features.flexible": "Belajar Fleksibel",
    "elearning.features.flexibleDesc": "Akses materi kapan saja dan di mana saja sesuai kenyamanan Anda",
    "elearning.features.interactive": "Interaktif",
    "elearning.features.interactiveDesc": "Belajar dengan metode yang menarik dan interaktif",
    "elearning.benefits.title": "Manfaat E-Learning",
    "elearning.benefits.b1": "Akses materi 24/7 dari mana saja",
    "elearning.benefits.b2": "Belajar dengan tempo sendiri",
    "elearning.benefits.b3": "Materi terupdate secara berkala",
    "elearning.benefits.b4": "Diskusi langsung dengan guru",
    "elearning.benefits.b5": "Quiz dengan feedback instan",
    "elearning.benefits.b6": "Tracking perkembangan belajar",
    "elearning.guide.badge": "Cara Mengakses",
    "elearning.guide.title": "Mulai Belajar Online",
    "elearning.guide.forStudents": "Untuk Siswa",
    "elearning.guide.studentStep1": "Login menggunakan NIS",
    "elearning.guide.studentStep2": "Password default: tanggal lahir",
    "elearning.guide.studentStep3": "Akses kelas sesuai jadwal",
    "elearning.guide.forTeachers": "Untuk Guru",
    "elearning.guide.teacherStep1": "Login menggunakan NIP",
    "elearning.guide.teacherStep2": "Password default: tanggal lahir",
    "elearning.guide.teacherStep3": "Upload materi dan buat quiz",
    "elearning.cta.title": "Siap Belajar Digital?",
    "elearning.cta.subtitle": "Akses platform e-learning dan mulai belajar dengan cara yang lebih modern",
    "elearning.cta.access": "Akses E-Learning",
    "elearning.cta.help": "Butuh Bantuan?",
    "elearning.cta.comingSoon": "* Platform E-Learning dalam pengembangan. Segera hadir!",

    // Perpustakaan Page
    "perpustakaan.hero.badge": "Perpustakaan Digital",
    "perpustakaan.hero.title": "Jelajahi Dunia",
    "perpustakaan.hero.title2": "Tanpa Batas",
    "perpustakaan.hero.subtitle": "Koleksi digital lengkap untuk mendukung proses belajar dan literasi akademik",
    "perpustakaan.stats.collection": "Koleksi",
    "perpustakaan.stats.access": "Akses Online",
    "perpustakaan.stats.categories": "Kategori",
    "perpustakaan.stats.free": "Untuk Siswa",
    "perpustakaan.features.badge": "Fitur Perpustakaan",
    "perpustakaan.features.title": "Fasilitas & Layanan Digital",
    "perpustakaan.features.subtitle": "Nikmati kemudahan mengakses koleksi perpustakaan secara digital",
    "perpustakaan.features.search": "Pencarian Cepat",
    "perpustakaan.features.searchDesc": "Temukan buku dengan fitur search yang canggih",
    "perpustakaan.features.ebook": "Koleksi E-Book",
    "perpustakaan.features.ebookDesc": "Ribuan e-book dalam berbagai kategori dan mata pelajaran",
    "perpustakaan.features.journal": "Jurnal & Artikel",
    "perpustakaan.features.journalDesc": "Akses jurnal ilmiah dan artikel pendidikan terbaru",
    "perpustakaan.features.borrowing": "Peminjaman Digital",
    "perpustakaan.features.borrowingDesc": "Pinjam buku digital dengan sistem yang mudah",
    "perpustakaan.features.access247": "Akses 24/7",
    "perpustakaan.features.access247Desc": "Akses perpustakaan kapan saja, di mana saja",
    "perpustakaan.features.recommendation": "Rekomendasi",
    "perpustakaan.features.recommendationDesc": "Dapatkan rekomendasi bacaan berdasarkan minat Anda",
    "perpustakaan.collection.title": "Koleksi Kami",
    "perpustakaan.collection.books": "Buku Pelajaran",
    "perpustakaan.collection.journals": "Jurnal Ilmiah",
    "perpustakaan.collection.thesis": "Skripsi & Tesis",
    "perpustakaan.collection.general": "E-Book Umum",
    "perpustakaan.rules.badge": "Peraturan Peminjaman",
    "perpustakaan.rules.card": "Kartu Perpustakaan",
    "perpustakaan.rules.cardDesc": "Setiap siswa mendapatkan kartu perpustakaan digital yang digunakan untuk meminjam buku",
    "perpustakaan.rules.period": "Masa Peminjaman",
    "perpustakaan.rules.periodDesc": "Buku fisik: 7 hari, E-book: 14 hari. Dapat diperpanjang jika tidak ada antrian",
    "perpustakaan.rules.fine": "Denda Keterlambatan",
    "perpustakaan.rules.fineDesc": "Rp 500 per hari untuk buku fisik. E-book tidak ada denda keterlambatan",
    "perpustakaan.rules.limit": "Batas Peminjaman",
    "perpustakaan.rules.limitDesc": "Maksimal 3 buku fisik dan 5 e-book per siswa",
    "perpustakaan.hours.badge": "Jam Operasional",
    "perpustakaan.hours.monThu": "Senin - Kamis",
    "perpustakaan.hours.monThuTime": "07.30 - 15.30 WIB",
    "perpustakaan.hours.fri": "Jumat",
    "perpustakaan.hours.friTime": "07.30 - 11.30 WIB",
    "perpustakaan.hours.sat": "Sabtu",
    "perpustakaan.hours.satTime": "08.00 - 12.00 WIB",
    "perpustakaan.hours.sun": "Minggu",
    "perpustakaan.hours.sunTime": "Tutup",
    "perpustakaan.hours.note": "Catatan",
    "perpustakaan.hours.noteDesc": "Perpustakaan digital dapat diakses 24/7 melalui website",
    "perpustakaan.cta.title": "Mulai Membaca Hari Ini",
    "perpustakaan.cta.subtitle": "Akses koleksi perpustakaan digital dan tingkatkan literasi Anda",
    "perpustakaan.cta.access": "Akses Perpustakaan",
    "perpustakaan.cta.help": "Butuh Bantuan?",
    "perpustakaan.cta.comingSoon": "* Perpustakaan Digital dalam pengembangan. Segera hadir!",

    // Image Compressor Page
    "compressor.hero.badge": "Tools",
    "compressor.hero.title": "Kompres Gambar",
    "compressor.hero.subtitle": "Kecilkan ukuran gambar tanpa mengurangi kualitas secara signifikan",
    "compressor.settings.title": "Pengaturan Kompresi",
    "compressor.settings.quality": "Kualitas",
    "compressor.settings.maxWidth": "Lebar Maksimal",
    "compressor.settings.scale": "Skala",
    "compressor.upload.title": "Pilih atau Seret Gambar ke Sini",
    "compressor.upload.processing": "Memproses...",
    "compressor.upload.subtitle": "JPG, PNG, WebP - Maksimal 10MB per gambar",
    "compressor.upload.button": "Pilih Gambar",
    "compressor.results.title": "Hasil Kompresi",
    "compressor.results.clear": "Hapus Semua",
    "compressor.results.downloadAll": "Download Semua",
    "compressor.image.original": "ORIGINAL",
    "compressor.image.compressed": "KOMPRESI",
    "compressor.image.savings": "Hemat",
    "compressor.image.download": "Download",
    "compressor.tips.title": "Tips Kompresi Gambar",
    "compressor.tips.tip1": "Untuk foto gunakan kualitas 70-80% untuk hasil terbaik",
    "compressor.tips.tip2": "Untuk grafik/diagram gunakan kualitas 90-100%",
    "compressor.tips.tip3": "Lebar 1920px sudah cukup untuk tampilan web",
    "compressor.tips.tip4": "Format JPEG lebih kecil untuk foto, PNG untuk grafik",
    "compressor.cta.title": "Butuh Tools Lainnya?",
    "compressor.cta.subtitle": "Jelajahi tools lain yang tersedia untuk membantu produktivitas Anda",
    "compressor.cta.home": "Kembali ke Beranda",
  },
  en: {
    "nav.about": "About YAPIM",
    "nav.academic": "Education & Academic",
    "nav.life": "Student Life",
    "nav.news": "News & Announcements",
    "nav.admission": "Admission",
    "nav.alumni": "Alumni & Career",
    "nav.staff": "Teachers & Staff",
    "hero.badge": "Welcome to the Official Portal",
    "hero.title": "Building Excellent & Characterful Generations",
    "hero.subtitle": "SMA-SMKS YAPIM Taruna Pandan is dedicated to producing future leaders through high-quality education, moral integrity, and global insight.",
    "cta.primary": "Get to Know Us Closer",
    "cta.secondary": "Explore Facilities",
    "welcome.badge": "Principal's Welcome",
    "welcome.title": "Dedicated to Educational Excellence in North Sumatra",
    "welcome.subtitle": "Our vision is to form competent and religious future leaders.",
    "welcome.quote": "Education is not just a transfer of knowledge, but a long process in forming the character, ethics, and moral foundation of future generations.",
    "welcome.name": "Parunggulan Tobing",
    "welcome.role": "Principal of SMA-SMKS YAPIM",
    "stats.title": "Institutional Achievements",
    "stats.students": "Active Students",
    "stats.alumni": "Successful Alumni",
    "stats.staff": "Teachers & Staff",
    "stats.graduation": "Graduation Rate",
    "footer.desc": "A leading senior high school in North Sumatra dedicated to producing graduates with academic excellence, noble character, and global insight.",
    "footer.links": "Quick Links",
    "footer.services": "Online Services",
    "footer.contact": "Contact Us",
    "lang.switch": "Bahasa Indonesia",

    // Privacy Page
    "privacy.hero.badge": "Legal & Privacy",
    "privacy.hero.title": "Privacy Policy",
    "privacy.hero.subtitle": "Your personal data protection is our priority",
    "privacy.lastUpdated": "Last Updated",
    "privacy.intro.title": "Introduction",
    "privacy.intro.p1": "SMA-SMKS YAPIM Taruna Pandan (\"we\") is committed to protecting and respecting your privacy. This Privacy Policy explains how we collect, use, disclose, and protect your personal information when you use our website.",
    "privacy.intro.p2": "By accessing or using our website, you agree to the collection and use of information in accordance with this policy.",
    "privacy.data.title": "Data We Collect",
    "privacy.data.personal": "Information You Provide",
    "privacy.data.auto": "Automatically Collected Information",
    "privacy.usage.title": "How We Use Your Data",
    "privacy.usage.education": "For Education",
    "privacy.usage.eduDesc": "Manage learning, grades, and student attendance",
    "privacy.usage.communication": "For Communication",
    "privacy.usage.commDesc": "Send important information to parents and students",
    "privacy.usage.registration": "For Registration",
    "privacy.usage.regDesc": "Process new student registrations (PPDB)",
    "privacy.usage.improvement": "For Improvement",
    "privacy.usage.impDesc": "Improve service quality and website",
    "privacy.rights.title": "Your Rights over Personal Data",
    "privacy.rights.access": "Access",
    "privacy.rights.accessDesc": "You have the right to know what data we store about you",
    "privacy.rights.correct": "Correct",
    "privacy.rights.correctDesc": "You can update inaccurate data",
    "privacy.rights.delete": "Delete",
    "privacy.rights.deleteDesc": "You can request deletion of your personal data",
    "privacy.rights.reject": "Reject",
    "privacy.rights.rejectDesc": "You can refuse data usage for certain purposes",
    "privacy.security.title": "Data Security",
    "privacy.security.desc": "We implement various security measures to protect your personal data",
    "privacy.security.encryption": "Data encryption during transmission",
    "privacy.security.access": "Limited access for authorized personnel",
    "privacy.security.audit": "Regular security audits",
    "privacy.security.backup": "Regular data backups",
    "privacy.contact.title": "Questions about Privacy?",
    "privacy.contact.desc": "If you have questions about this Privacy Policy or our treatment of your personal data, please contact us",
    "privacy.cta.title": "Need Other Help?",
    "privacy.cta.subtitle": "Our team is ready to help you with any questions or needs",
    "privacy.cta.help": "Help Center",
    "privacy.cta.contact": "Contact Us",

    // Terms Page
    "terms.hero.badge": "Legal & Terms",
    "terms.hero.title": "Terms & Conditions",
    "terms.hero.subtitle": "Terms of use for SMA-SMKS YAPIM Taruna Pandan website and services",
    "terms.lastUpdated": "Last Updated",
    "terms.intro.title": "1. Introduction",
    "terms.intro.p1": "Welcome to the official website of SMA-SMKS YAPIM Taruna Pandan. By accessing or using our website, you agree to be bound by these Terms & Conditions.",
    "terms.intro.p2": "If you do not agree with any part of these terms, please do not use our website.",
    "terms.usage.title": "2. Website Usage Terms",
    "terms.usage.age": "User Age",
    "terms.usage.ageDesc": "This website is intended for users aged 18 and above. Users under 18 must be supervised by parents or guardians.",
    "terms.usage.account": "User Account",
    "terms.usage.accountDesc": "You are responsible for maintaining the confidentiality of your account information and restricting access to your computer or device.",
    "terms.usage.prohibited": "Prohibited Behavior",
    "terms.usage.prohibitedDesc": "Using the website for illegal purposes, attempting to hack or damage security systems, uploading harmful content, sending spam or unwanted messages, impersonating others.",
    "terms.copyright.title": "3. Copyright & Content",
    "terms.copyright.ownership": "Content Ownership",
    "terms.copyright.ownershipDesc": "All content on this website (text, images, logos, videos) is the copyright of SMA-SMKS YAPIM Taruna Pandan or authorized third parties.",
    "terms.copyright.allowed": "Allowed Usage",
    "terms.copyright.allowedDesc": "You are allowed to view, download, or print content for personal and non-commercial use.",
    "terms.copyright.prohibited": "Prohibited Usage",
    "terms.copyright.prohibitedDesc": "Modifying, distributing, or using content for commercial purposes without our written permission is prohibited.",
    "terms.liability.title": "4. Limitation of Liability",
    "terms.liability.desc": "Our website is provided \"as is\" without any warranties. We do not guarantee:",
    "terms.liability.availability": "Website will always be available or error-free",
    "terms.liability.accuracy": "Information on the website is accurate or complete",
    "terms.liability.security": "Website is safe from viruses or other harmful components",
    "terms.privacy.title": "5. Privacy & Personal Data",
    "terms.privacy.desc": "Your use of personal data is governed by our Privacy Policy. By using this website, you agree to data processing in accordance with that policy.",
    "terms.privacy.link": "View Privacy Policy →",
    "terms.changes.title": "6. Changes to Terms",
    "terms.changes.desc": "We reserve the right to change these Terms & Conditions at any time. Changes will be displayed on this page and the \"Last Updated\" date will be updated. Continued use after changes means you accept the new terms.",
    "terms.contact.title": "7. Contact Us",
    "terms.contact.desc": "If you have questions about these Terms & Conditions, please contact us",
    "terms.contact.email": "Email",
    "terms.contact.phone": "Phone",
    "terms.contact.button": "Contact Us",
    "terms.cta.title": "Need More Information?",
    "terms.cta.subtitle": "Our team is ready to help answer your questions",
    "terms.cta.help": "Help Center",
    "terms.cta.contact": "Contact Us",

    // Karir Page
    "karir.hero.badge": "Career & Alumni",
    "karir.hero.title": "Join Our Team",
    "karir.hero.subtitle": "Build a career in education or connect with our alumni network",
    "karir.stats.teachers": "Teachers & Staff",
    "karir.stats.alumni": "Alumni",
    "karir.stats.experience": "Years Experience",
    "karir.stats.accreditation": "Accreditation",
    "karir.positions.badge": "Open Positions",
    "karir.positions.title": "Available Positions",
    "karir.positions.subtitle": "Join our team of professional educators to shape excellent generations",
    "karir.positions.fullTime": "Full Time",
    "karir.positions.requirements": "Requirements",
    "karir.positions.apply": "Apply Now",
    "karir.positions.spontan": "Send Spontaneous CV",
    "karir.positions.noPosition": "Can't find a suitable position? Send us your CV for future consideration.",
    "karir.alumni.badge": "Alumni Network",
    "karir.alumni.title": "Benefits of Being an Alumni",
    "karir.alumni.subtitle": "Join the YAPIM alumni network for various career and professional benefits",
    "karir.alumni.networking": "Networking",
    "karir.alumni.networkingDesc": "Connect with thousands of YAPIM alumni",
    "karir.alumni.career": "Career Info",
    "karir.alumni.careerDesc": "Access exclusive job opportunities",
    "karir.alumni.events": "Alumni Events",
    "karir.alumni.eventsDesc": "Regular reunions and gatherings",
    "karir.alumni.mentoring": "Mentoring",
    "karir.alumni.mentoringDesc": "Student mentoring programs",
    "karir.testimonials.badge": "Testimonials",
    "karir.testimonials.title": "Words from Alumni & Teachers",
    "karir.cta.title": "Ready to Join?",
    "karir.cta.subtitle": "Be part of YAPIM's education team or join our alumni network",
    "karir.cta.apply": "Apply Now",
    "karir.cta.alumni": "Alumni Portal",

    // Bantuan Page
    "bantuan.hero.badge": "Help Center",
    "bantuan.hero.title": "How Can We Help?",
    "bantuan.hero.subtitle": "Find answers to common questions or contact our team",
    "bantuan.quicklinks.title": "Quickly Find What You Need",
    "bantuan.quicklinks.ppdb": "New Student Registration",
    "bantuan.quicklinks.akademik": "Academic Information",
    "bantuan.quicklinks.kontak": "Contact Us",
    "bantuan.quicklinks.galeri": "School Gallery",
    "bantuan.quicklinks.karir": "Career & Alumni",
    "bantuan.faq.badge": "FAQ",
    "bantuan.faq.title": "Frequently Asked Questions",
    "bantuan.faq.subtitle": "Find answers to common questions about registration, academics, and school facilities",
    "bantuan.faq.q1.question": "How do I register as a new student (PPDB)?",
    "bantuan.faq.q1.answer": "New student registration can be done online through the PPDB page on our website. You need to fill out the registration form, upload required documents (graduation certificate, family card, birth certificate), and pay the registration fee. Complete information is available on the /ppdb page.",
    "bantuan.faq.q2.question": "What are the registration requirements for SMA and SMK?",
    "bantuan.faq.q2.answer": "For SMA: Graduated from SMP/MTs with minimum GPA of 75. For SMK: Graduated from SMP/MTs with specific requirements per major (TKR requires good physical condition, TKJ interested in computer networks, etc.). Required documents: Graduation Certificate/SKL, Family Card, Birth Certificate, and Photo.",
    "bantuan.faq.q3.question": "How do I contact the school?",
    "bantuan.faq.q3.answer": "You can contact us through: Phone (0631) 372375, Email: yapim_pandan@yahoo.com, or visit us directly at JL. AHMAD YANI PANDAN. Operating hours: Monday - Friday, 07.00 - 15.00 WIB.",
    "bantuan.faq.q4.question": "Are there scholarships for outstanding students?",
    "bantuan.faq.q4.answer": "Yes, YAPIM provides scholarships for academically and non-academically outstanding students. Scholarships are awarded based on semester grade evaluations and achievements at district/provincial/national levels. Contact the student affairs division for more information.",
    "bantuan.faq.q5.question": "How does the e-learning system work at YAPIM?",
    "bantuan.faq.q5.answer": "YAPIM uses an e-learning platform to support hybrid learning. Students can access materials, assignments, and quizzes online. Login using the NIS provided during registration. Complete guide is available on the /elearning page.",
    "bantuan.faq.q6.question": "What majors are available at SMK?",
    "bantuan.faq.q6.answer": "SMK YAPIM Taruna Pandan offers majors: 1) TKR (Automotive Engineering) - Automotive, 2) TKJ (Computer and Network Engineering) - IT and Networking. Both majors have complete facilities and industry partnerships.",
    "bantuan.contact.badge": "Contact Us",
    "bantuan.contact.title": "Still Have Questions?",
    "bantuan.contact.subtitle": "Our team is ready to help. Contact us through the following channels",
    "bantuan.contact.phoneTitle": "Phone",
    "bantuan.contact.emailTitle": "Email",
    "bantuan.contact.addressTitle": "Address",
    "bantuan.contact.hoursTitle": "Operating Hours",
    "bantuan.contact.call": "Contact",
    "bantuan.contact.fullForm": "View Full Contact Form",
    "bantuan.cta.title": "Want to Talk to Our Team?",
    "bantuan.cta.subtitle": "We're ready to help answer your questions and provide the support you need",
    "bantuan.cta.email": "Send Email",
    "bantuan.cta.phone": "Phone",

    // Portal Siswa Page
    "portal.hero.badge": "Student Portal",
    "portal.hero.title": "Student Information System",
    "portal.hero.subtitle": "Access schedules, grades, and academic information in one integrated portal",
    "portal.stats.access": "Access",
    "portal.stats.students": "Active Students",
    "portal.stats.features": "Main Features",
    "portal.stats.digital": "Digital",
    "portal.features.title": "Everything You Need",
    "portal.features.subtitle": "Student portal provides various features to facilitate learning activities",
    "portal.features.schedule": "Class Schedule",
    "portal.features.scheduleDesc": "Access complete class schedules for each semester",
    "portal.features.grades": "Grades & Report Cards",
    "portal.features.gradesDesc": "View assignment, exam, and semester grades online",
    "portal.features.attendance": "Attendance",
    "portal.features.attendanceDesc": "Monitor attendance and daily attendance records",
    "portal.features.materials": "Learning Materials",
    "portal.features.materialsDesc": "Access learning materials and digital resources",
    "portal.features.erapor": "E-Report Card",
    "portal.features.eraporDesc": "Integrated electronic report card system",
    "portal.features.profile": "Personal Data",
    "portal.features.profileDesc": "Manage personal data and academic information",
    "portal.login.badge": "How to Login",
    "portal.login.title": "Access Student Portal",
    "portal.login.subtitle": "Follow these simple steps to access the student portal",
    "portal.login.step1": "Open Portal Page",
    "portal.login.step1Desc": "Visit the student portal page through the button below",
    "portal.login.step2": "Enter NIS",
    "portal.login.step2Desc": "Use Student ID Number as username",
    "portal.login.step3": "Enter Password",
    "portal.login.step3Desc": "Default password is birth date (DDMMYYYY)",
    "portal.login.step4": "Change Password",
    "portal.login.step4Desc": "Change password immediately after first login",
    "portal.login.forgot": "Forgot Password?",
    "portal.login.forgotDesc": "Contact school admin for reset",
    "portal.parent.badge": "For Parents",
    "portal.parent.title": "Monitor Your Child in Real-Time",
    "portal.parent.subtitle": "Student portal also makes it easy for parents to monitor their child's academic progress",
    "portal.parent.performance": "Monitor Child Performance",
    "portal.parent.performanceDesc": "Parents can monitor grades, attendance, and learning activities in real-time",
    "portal.parent.communication": "Communicate with Teachers",
    "portal.parent.communicationDesc": "Contact homeroom or subject teachers directly through the portal",
    "portal.parent.calendar": "Academic Calendar Info",
    "portal.parent.calendarDesc": "Access exam schedules, holidays, and important school events",
    "portal.cta.title": "Ready to Access Student Portal?",
    "portal.cta.subtitle": "Login now to access all your academic information",
    "portal.cta.login": "Login to Portal",
    "portal.cta.help": "Need Help?",
    "portal.cta.comingSoon": "* Student Portal in development. Coming soon!",

    // E-Learning Page
    "elearning.hero.badge": "YAPIM E-Learning",
    "elearning.hero.title": "Digital Learning,",
    "elearning.hero.title2": "Brighter Future",
    "elearning.hero.subtitle": "Modern online learning platform for SMA-SMKS YAPIM Taruna Pandan students",
    "elearning.stats.materials": "Active Materials",
    "elearning.stats.students": "Students",
    "elearning.stats.access": "Access",
    "elearning.stats.online": "Online",
    "elearning.about.badge": "About E-Learning",
    "elearning.about.title": "What is YAPIM E-Learning?",
    "elearning.about.desc": "YAPIM E-Learning is a digital learning platform designed to support hybrid teaching and learning. Students can access materials, complete assignments, and discuss with teachers online anytime and anywhere.",
    "elearning.about.forStudents": "For Students",
    "elearning.about.forStudentsDesc": "Learn more flexibly with digital materials access, online assignments, and discussions with classmates.",
    "elearning.about.forTeachers": "For Teachers",
    "elearning.about.forTeachersDesc": "Manage digital learning easily. Upload materials, create quizzes, and monitor student progress.",
    "elearning.features.badge": "Key Features",
    "elearning.features.title": "Why YAPIM E-Learning?",
    "elearning.features.digitalMaterials": "Digital Materials",
    "elearning.features.digitalMaterialsDesc": "Access learning materials in various formats: text, video, and slides",
    "elearning.features.quiz": "Quiz & Assignment",
    "elearning.features.quizDesc": "Complete assignments and exams online with automatic grading system",
    "elearning.features.forum": "Discussion Forum",
    "elearning.features.forumDesc": "Discuss with teachers and classmates online",
    "elearning.features.tracking": "Progress Tracking",
    "elearning.features.trackingDesc": "Monitor learning progress and achievements",
    "elearning.features.flexible": "Flexible Learning",
    "elearning.features.flexibleDesc": "Access materials anytime and anywhere as per your convenience",
    "elearning.features.interactive": "Interactive",
    "elearning.features.interactiveDesc": "Learn with engaging and interactive methods",
    "elearning.benefits.title": "Benefits of E-Learning",
    "elearning.benefits.b1": "Access materials 24/7 from anywhere",
    "elearning.benefits.b2": "Learn at your own pace",
    "elearning.benefits.b3": "Materials updated regularly",
    "elearning.benefits.b4": "Direct discussion with teachers",
    "elearning.benefits.b5": "Quiz with instant feedback",
    "elearning.benefits.b6": "Track learning progress",
    "elearning.guide.badge": "How to Access",
    "elearning.guide.title": "Start Online Learning",
    "elearning.guide.forStudents": "For Students",
    "elearning.guide.studentStep1": "Login using NIS",
    "elearning.guide.studentStep2": "Default password: birth date",
    "elearning.guide.studentStep3": "Access classes according to schedule",
    "elearning.guide.forTeachers": "For Teachers",
    "elearning.guide.teacherStep1": "Login using NIP",
    "elearning.guide.teacherStep2": "Default password: birth date",
    "elearning.guide.teacherStep3": "Upload materials and create quizzes",
    "elearning.cta.title": "Ready for Digital Learning?",
    "elearning.cta.subtitle": "Access the e-learning platform and start learning the modern way",
    "elearning.cta.access": "Access E-Learning",
    "elearning.cta.help": "Need Help?",
    "elearning.cta.comingSoon": "* E-Learning Platform in development. Coming soon!",

    // Perpustakaan Page
    "perpustakaan.hero.badge": "Digital Library",
    "perpustakaan.hero.title": "Explore the World",
    "perpustakaan.hero.title2": "Without Limits",
    "perpustakaan.hero.subtitle": "Complete digital collection to support learning and academic literacy",
    "perpustakaan.stats.collection": "Collection",
    "perpustakaan.stats.access": "Online Access",
    "perpustakaan.stats.categories": "Categories",
    "perpustakaan.stats.free": "For Students",
    "perpustakaan.features.badge": "Library Features",
    "perpustakaan.features.title": "Digital Facilities & Services",
    "perpustakaan.features.subtitle": "Enjoy easy access to library collections digitally",
    "perpustakaan.features.search": "Fast Search",
    "perpustakaan.features.searchDesc": "Find books with advanced search features",
    "perpustakaan.features.ebook": "E-Book Collection",
    "perpustakaan.features.ebookDesc": "Thousands of e-books in various categories and subjects",
    "perpustakaan.features.journal": "Journals & Articles",
    "perpustakaan.features.journalDesc": "Access scientific journals and latest education articles",
    "perpustakaan.features.borrowing": "Digital Borrowing",
    "perpustakaan.features.borrowingDesc": "Borrow digital books with an easy system",
    "perpustakaan.features.access247": "24/7 Access",
    "perpustakaan.features.access247Desc": "Access library anytime, anywhere",
    "perpustakaan.features.recommendation": "Recommendations",
    "perpustakaan.features.recommendationDesc": "Get reading recommendations based on your interests",
    "perpustakaan.collection.title": "Our Collection",
    "perpustakaan.collection.books": "Textbooks",
    "perpustakaan.collection.journals": "Scientific Journals",
    "perpustakaan.collection.thesis": "Thesis & Dissertations",
    "perpustakaan.collection.general": "General E-Books",
    "perpustakaan.rules.badge": "Borrowing Rules",
    "perpustakaan.rules.card": "Library Card",
    "perpustakaan.rules.cardDesc": "Each student gets a digital library card used to borrow books",
    "perpustakaan.rules.period": "Borrowing Period",
    "perpustakaan.rules.periodDesc": "Physical books: 7 days, E-books: 14 days. Can be extended if no queue",
    "perpustakaan.rules.fine": "Late Fee",
    "perpustakaan.rules.fineDesc": "Rp 500 per day for physical books. E-books have no late fee",
    "perpustakaan.rules.limit": "Borrowing Limit",
    "perpustakaan.rules.limitDesc": "Maximum 3 physical books and 5 e-books per student",
    "perpustakaan.hours.badge": "Operating Hours",
    "perpustakaan.hours.monThu": "Monday - Thursday",
    "perpustakaan.hours.monThuTime": "07.30 - 15.30 WIB",
    "perpustakaan.hours.fri": "Friday",
    "perpustakaan.hours.friTime": "07.30 - 11.30 WIB",
    "perpustakaan.hours.sat": "Saturday",
    "perpustakaan.hours.satTime": "08.00 - 12.00 WIB",
    "perpustakaan.hours.sun": "Sunday",
    "perpustakaan.hours.sunTime": "Closed",
    "perpustakaan.hours.note": "Note",
    "perpustakaan.hours.noteDesc": "Digital library can be accessed 24/7 through the website",
    "perpustakaan.cta.title": "Start Reading Today",
    "perpustakaan.cta.subtitle": "Access the digital library collection and improve your literacy",
    "perpustakaan.cta.access": "Access Library",
    "perpustakaan.cta.help": "Need Help?",
    "perpustakaan.cta.comingSoon": "* Digital Library in development. Coming soon!",

    // Image Compressor Page
    "compressor.hero.badge": "Tools",
    "compressor.hero.title": "Compress Image",
    "compressor.hero.subtitle": "Reduce image size without significantly reducing quality",
    "compressor.settings.title": "Compression Settings",
    "compressor.settings.quality": "Quality",
    "compressor.settings.maxWidth": "Max Width",
    "compressor.settings.scale": "Scale",
    "compressor.upload.title": "Choose or Drop Images Here",
    "compressor.upload.processing": "Processing...",
    "compressor.upload.subtitle": "JPG, PNG, WebP - Max 10MB per image",
    "compressor.upload.button": "Choose Images",
    "compressor.results.title": "Compression Results",
    "compressor.results.clear": "Clear All",
    "compressor.results.downloadAll": "Download All",
    "compressor.image.original": "ORIGINAL",
    "compressor.image.compressed": "COMPRESSED",
    "compressor.image.savings": "Saved",
    "compressor.image.download": "Download",
    "compressor.tips.title": "Image Compression Tips",
    "compressor.tips.tip1": "Use 70-80% quality for photos for best results",
    "compressor.tips.tip2": "Use 90-100% quality for graphics/diagrams",
    "compressor.tips.tip3": "1920px width is sufficient for web display",
    "compressor.tips.tip4": "JPEG is smaller for photos, PNG for graphics",
    "compressor.cta.title": "Need Other Tools?",
    "compressor.cta.subtitle": "Explore other available tools to help your productivity",
    "compressor.cta.home": "Back to Home",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("id");

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations["id"]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
